### ISSUE TITLE
Messages from a same user should be grouped when they are consecutive

### ISSUE THREAD

**Issue by Pacane** [woven/tracker#2]
When a user send multiple messages in a row, it should group them together instead of displaying them in separate message blocks.

**Comment by davenotik** [comment]
So that's basically `List<MessageGroup>` where `MessageGroup` is  `{ user: User, messages: List<Message>}`.

**Comment by davenotik** [comment]
Maybe `List<Map<String, List<Item>>>` so it's a loopable list of maps, where the keys are usernames, and the values are lists of grouped items.

**Comment by Pacane** [comment]
Are usernames unique?

**Comment by davenotik** [comment]
Yes, usernames are unique. Aren't they always?

**Comment by Pacane** [comment]
I don't know, it depends on how you implement it

**Comment by Pacane** [comment]
By that I mean, if eventually you want to support organizations, do you
want 2 users in different organizations to be able to have the same name?

**Comment by davenotik** [comment]
Boom! Refactored a bunch to make this possible. Pretty sophisticated algorithm actually. It's live.
